# Generated by Django 4.1.7 on 2023-03-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('Departement_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Departement_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('Employee_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Employee_Name', models.CharField(max_length=100)),
                ('Departement', models.CharField(max_length=100)),
                ('Dataofjoin', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
